package org.tempuri;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2019-02-21T01:01:07.280+04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "DataAccess_TransactionStatusSoap")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T01:01:07.280+04:00", comments = "Apache CXF 3.1.7")
public interface DataAccessTransactionStatusSoap {

    @WebMethod(operationName = "GetTransactionInfo", action = "http://tempuri.org/GetTransactionInfo")
    @RequestWrapper(localName = "GetTransactionInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTransactionInfo")
    @ResponseWrapper(localName = "GetTransactionInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTransactionInfoResponse")
    @WebResult(name = "GetTransactionInfoResult", targetNamespace = "http://tempuri.org/")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T01:01:07.280+04:00")
    public org.tempuri.ArrayOfDataTable getTransactionInfo(
        @WebParam(name = "ApplicationNo", targetNamespace = "http://tempuri.org/")
        java.lang.String applicationNo,
        @WebParam(name = "LicenseNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String licenseNumber,
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/", header = true)
        Authentication authentication
    );
}
